version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyPassword
      MYSQL_DATABASE: todos
      MYSQL_USER: root
      MYSQL_PASSWORD: MyPassword
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
